language: go
go:
- 1.6.3
- 1.7
- tip
branches:
  only:
  - develop
  - master
install:
  - go get github.com/naoina/toml
  - go get github.com/go-ldap/ldap
  - go get github.com/keltia/erc-search/config
