language: go
go:
- "1.12.x"
- master
matrix:
  allow_failures:
  - go: master
branches:
  only:
  - develop
  - master
install:
  - go get github.com/BurntSushi/toml
  - go get gopkg.in/ldap.v2
  - go get github.com/pkg/errors
