site: ldap.eurocontrol.fr
port: 389
ldap_base: ou=eurousers,o=eurocontrol,o=ec
ldap_filter: (&(objectclass=eurocontrolperson)(%s=*%s*))
ldap_attrs:
  - ksn
  - kgivenname
  - telephonenumber
  - eurocontrolroomid
  - mail
  - uid
  - eurocontrolunitcode
  - eurocontrolgrade
