site: ldap.eurocontrol.fr
port: 389
ldapbase: ou=eurousers,o=eurocontrol,o=ec
ldapfilter: (&(objectclass=eurocontrolperson)(%s=*%s*))
attrs:
  - ksn
  - kgivenname
  - telephonenumber
  - eurocontrolroomid
  - mail
  - uid
  - eurocontrolunitcode
  - eurocontrolgrade
